name: TransplantTissueClassification

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.9
  - jupyterlab=3
  - pandas=1.4.2
  - matplotlib=3.5.1
  - joblib=1.0.1
  - seaborn=0.11.2
  - ipywidgets=7.6.2
  - scikit-learn=0.23.2